# Generated by Django 5.2.4 on 2025-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
